project_id = "rwhdtmcqtpfwemasjfag"

[functions.stripe-webhook]
verify_jwt = false

[functions.get-heart-by-session]
verify_jwt = false

[functions.reset-demo-hearts]
verify_jwt = false

[functions.increment-demo-count]
verify_jwt = false